### PR TITLE
(DOCSP-890, DOCS-10602): Updated JDBC connection and Release Notes.

### PR DESCRIPTION
**Pull request by atsansone**
@breinero : Please review:

- [JDBC Auth Plugin Install](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-10602/tutorial/install-auth-plugin-jdbc.html#install-jdbc-authentication-plugin)
- [Release Notes update](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-10602/release-notes.html#bi-2-2-0)

### CODE REVIEW

**Comment by breinero** [comment]
One minor nit, which was caused by me: Could we transpose the words "Provide mongosqld" to Mongosqld provides in the bullet describing SHOW STATUS please?

**Comment by breinero** [comment]
RE: JDBC Auth Plugin Install, LGTM

**Comment by atsansone** [comment]
I had to make the release notes parallel: It's all _verb_ _noun_. The unsaid subject is _"This release..."_

**Comment by breinero** [comment]
LGTM

**Pull request closed without merging**
